# coding: utf-8

from __future__ import annotations
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    name: str
    args: dict


class Completion(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Completion - a model defined in OpenAPI

        completion: The completion of this Completion.
        timestamp: The timestamp of this Completion.
    """

    completion: str = Field(alias="completion")
    timestamp: datetime = Field(alias="timestamp")
    tool_calls: Optional[List[ToolCall]] = None


Completion.update_forward_refs()
