version: "3"

services:
  build-genesis:
    platform: linux/amd64
    build:
      platforms:
        - "linux/amd64"
      context: "./genesis"
      dockerfile: Dockerfile
      args:
        SUI_TAG: ${SUI_TAG} # This will read the tag from the .env file
    volumes:
      - genesis-data:/opt/sui/genesis
    environment:
      - SUI_TAG=${SUI_TAG} # This ensures the environment variable is used for any other dynamic config
    restart: "no"

  validator1:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
    image: mysten/sui-node:testnet-v1.29.1
    container_name: validator1
    hostname: validator1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - ./genesis/files/validator1-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db1:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator2:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
    image: mysten/sui-node:testnet-v1.29.1
    container_name: validator2
    hostname: validator2
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - ./genesis/files/validator2-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db2:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator3:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
    image: mysten/sui-node:testnet-v1.29.1
    container_name: validator3
    hostname: validator3
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - ./genesis/files/validator3-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db3:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator4:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
    image: mysten/sui-node:testnet-v1.29.1
    container_name: validator4
    hostname: validator4
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - ./genesis/files/validator4-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db4:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  fullnode1:
    image: mysten/sui-tools:testnet-v1.29.1
    hostname: fullnode1
    container_name: fullnode1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - ./genesis/static/fullnode.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - /tmp/sui/db5:/opt/sui/db:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/fullnode.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
    depends_on:
      build-genesis:
        condition: service_completed_successfully

  faucet:
    image: mysten/sui-tools:testnet-v1.29.1
    hostname: faucet
    container_name: faucet
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - SUI_CONFIG_DIR=/opt/sui/config
      - WRITE_AHEAD_LOG="/opt/sui/faucet/wal.log"
      - HOST_IP=0.0.0.0
    volumes:
      - ./genesis/static/client.yaml:/opt/sui/config/client.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - ./genesis/static/sui.keystore:/opt/sui/config/sui.keystore:ro
      - faucet-data:/opt/sui/faucet
    command:
      [
        "/usr/local/bin/sui-faucet",
        "--write-ahead-log",
        "/opt/sui/faucet/wal.log",
        "--host-ip",
        "0.0.0.0",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
    depends_on:
      build-genesis:
        condition: service_completed_successfully

volumes:
  genesis-data:
  faucet-data:
