version: "3"

services:
  build-suitools:
    restart: "no"
    image: sui-tools:${SUI_TAG}
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        SUI_TAG: ${SUI_TAG}

  build-genesis:
    image: sui-build-genesis:${SUI_TAG}
    container_name: build-genesis
    build:
      context: "./genesis"
      dockerfile: Dockerfile
      args:
        SUI_TAG: ${SUI_TAG}
    pull_policy: never
    volumes:
      - genesis-data:/opt/sui/genesis
    environment:
      - SUI_TAG=${SUI_TAG}
    restart: "no"
    depends_on:
      build-suitools:
        condition: service_completed_successfully

  validator1:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
      build-suitools:
        condition: service_completed_successfully
    image: sui-tools:${SUI_TAG}
    container_name: validator1
    hostname: validator1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - validator1-db:/opt/sui/db:rw
      - ./genesis/files/validator1-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator2:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
      build-suitools:
        condition: service_completed_successfully
    image: sui-tools:${SUI_TAG}
    container_name: validator2
    hostname: validator2
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - validator2-db:/opt/sui/db:rw
      - ./genesis/files/validator2-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator3:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
      build-suitools:
        condition: service_completed_successfully
    image: sui-tools:${SUI_TAG}
    container_name: validator3
    hostname: validator3
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - validator3-db:/opt/sui/db:rw
      - ./genesis/files/validator3-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  validator4:
    depends_on:
      build-genesis:
        condition: service_completed_successfully
      build-suitools:
        condition: service_completed_successfully
    image: sui-tools:${SUI_TAG}
    container_name: validator4
    hostname: validator4
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
    volumes:
      - genesis-data:/opt/sui/genesis
      - validator4-db:/opt/sui/db:rw
      - ./genesis/files/validator4-8080.yaml:/opt/sui/config/validator.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/validator.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
  fullnode1:
    image: sui-tools:${SUI_TAG}
    hostname: fullnode1
    container_name: fullnode1
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - RPC_WORKER_THREAD=12
      - NEW_CHECKPOINT_WARNING_TIMEOUT_MS=30000
      - NEW_CHECKPOINT_PANIC_TIMEOUT_MS=60000
      - SUI_CONFIG_DIR=/opt/sui/config
    volumes:
      - genesis-data:/opt/sui/genesis
      - fullnode1-db:/opt/sui/db:rw
      - ./genesis/static/fullnode.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - ./genesis/static/client.yaml:/opt/sui/config/client.yaml:rw
    command:
      [
        "/usr/local/bin/sui-node",
        "--config-path",
        "/opt/sui/config/fullnode.yaml",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
    depends_on:
      build-genesis:
        condition: service_completed_successfully
      build-suitools:
        condition: service_completed_successfully

  faucet:
    image: sui-tools:${SUI_TAG}
    hostname: faucet
    container_name: faucet
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sui_core=info,sui_network=info,sui_node=info,narwhal=info,narwhal-primary::helper=info,jsonrpsee=error
      - SUI_CONFIG_DIR=/opt/sui/config
      - HOST_IP=0.0.0.0
    volumes:
      - ./genesis/static/client.yaml:/opt/sui/config/client.yaml:rw
      - ./genesis/files/genesis.blob:/opt/sui/config/genesis.blob:ro
      - ./genesis/static/sui.keystore:/opt/sui/config/sui.keystore:ro
    command:
      [
        "/usr/local/bin/sui-faucet",
        "--write-ahead-log",
        "/tmp/faucet.wal",
        "--host-ip",
        "0.0.0.0",
      ]
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "1g"
    depends_on:
      build-genesis:
        condition: service_completed_successfully
      build-suitools:
        condition: service_completed_successfully

volumes:
  genesis-data:
  validator1-db:
  validator2-db:
  validator3-db:
  validator4-db:
  fullnode1-db:
  shared:
